### ISSUE TITLE
(Design Doc) Explain why there is no Message Controller 

### ISSUE THREAD

**Issue by wilgagne** [CSC207-UofT/course-project-newtapp#82]
Just so they don't think we forgot it or something. It could be in our design decision section.

**Comment by alexszokolay** [comment]
things to change/add in design doc:

- explain why we decided not to follow evan's advice not to implement a RequestModel design pattern:
                  we think that for it to work, based on our request model implementation, it would require a builder subclass for each implementation, which seems inproductive. tldr not worth it to spend time.
- Accessibility report
- a brief summary of what each group member has been working on since phase 1
- Each group member should include a link to a significant pull request
